package view;

import controller.ControllerProduto;
import static java.awt.event.KeyEvent.VK_ENTER;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelProduto;
import util.Formatador;

/**
 *
 * @author joao.samuel
 */
public class ViewProduto extends javax.swing.JFrame {
    
    ArrayList<ModelProduto> listaModelProdutos = new ArrayList<>();
    ControllerProduto controllerProdutos = new ControllerProduto();
    ModelProduto modelProdutos = new ModelProduto();
    String salvarAlterar;
    Formatador formatador = new Formatador();

    /**
     * Creates new form ViewProduto
     */
    public ViewProduto() {
        initComponents();
        carregarProdutos();
        setLocationRelativeTo(null);
        changeHabilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfCodigoProduto = new javax.swing.JTextField();
        jtfNomeProduto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfPesquisarProduto = new javax.swing.JTextField();
        jbPesquisarProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProduto = new javax.swing.JTable();
        jbCancelarProduto = new javax.swing.JButton();
        jbExcluirProduto = new javax.swing.JButton();
        jbEditarProduto = new javax.swing.JButton();
        jbNovoProduto = new javax.swing.JButton();
        jbSalvarProduto = new javax.swing.JButton();
        jtfEstoqueProduto = new javax.swing.JFormattedTextField();
        jtfValorProduto = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");

        jLabel1.setText("Código:");

        jLabel2.setText("Nome:");

        jtfCodigoProduto.setEditable(false);
        jtfCodigoProduto.setEnabled(false);
        jtfCodigoProduto.setMinimumSize(new java.awt.Dimension(22, 64));
        jtfCodigoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Estoque:");

        jLabel4.setText("Valor:");

        jLabel5.setText("Pesquisar:");

        jtfPesquisarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPesquisarProdutoKeyPressed(evt);
            }
        });

        jbPesquisarProduto.setText("Pesquisar");
        jbPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarProdutoActionPerformed(evt);
            }
        });

        jtProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Valor", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtProduto);
        if (jtProduto.getColumnModel().getColumnCount() > 0) {
            jtProduto.getColumnModel().getColumn(0).setMinWidth(70);
            jtProduto.getColumnModel().getColumn(0).setPreferredWidth(70);
            jtProduto.getColumnModel().getColumn(0).setMaxWidth(70);
            jtProduto.getColumnModel().getColumn(2).setMinWidth(80);
            jtProduto.getColumnModel().getColumn(2).setPreferredWidth(80);
            jtProduto.getColumnModel().getColumn(2).setMaxWidth(80);
            jtProduto.getColumnModel().getColumn(3).setMinWidth(80);
            jtProduto.getColumnModel().getColumn(3).setPreferredWidth(80);
            jtProduto.getColumnModel().getColumn(3).setMaxWidth(80);
        }

        jbCancelarProduto.setText("Cancelar");
        jbCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarProdutoActionPerformed(evt);
            }
        });

        jbExcluirProduto.setText("Excluir");
        jbExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirProdutoActionPerformed(evt);
            }
        });

        jbEditarProduto.setText("Editar");
        jbEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarProdutoActionPerformed(evt);
            }
        });

        jbNovoProduto.setText("Novo");
        jbNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNovoProdutoActionPerformed(evt);
            }
        });

        jbSalvarProduto.setText("Salvar");
        jbSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarProdutoActionPerformed(evt);
            }
        });

        jtfEstoqueProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        jtfValorProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfPesquisarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbPesquisarProduto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbCancelarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluirProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditarProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbNovoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbSalvarProduto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNomeProduto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jtfEstoqueProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(282, 282, 282)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCodigoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEstoqueProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbPesquisarProduto)
                    .addComponent(jtfPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelarProduto)
                    .addComponent(jbExcluirProduto)
                    .addComponent(jbEditarProduto)
                    .addComponent(jbNovoProduto)
                    .addComponent(jbSalvarProduto))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarProdutoActionPerformed
        // TODO add your handling code here:
        this.pesquisarProduto();
        
    }//GEN-LAST:event_jbPesquisarProdutoActionPerformed

    private void jtfCodigoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoProdutoActionPerformed

    private void jbSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarProdutoActionPerformed

        if(salvarAlterar.equals("salvar")) {
            this.salvarProduto();
        } else if (salvarAlterar.equals("alterar")) {
            this.alterarProduto();
        }  
    }//GEN-LAST:event_jbSalvarProdutoActionPerformed

    private void jbExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirProdutoActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = this.jtProduto.getSelectedRow();
        int codigoProdutoSelecionado = (int) jtProduto.getValueAt(linhaSelecionada, 0);
        
        if(controllerProdutos.excluirProdutoController(codigoProdutoSelecionado)) {
            JOptionPane.showMessageDialog(this, "Produto excluido com sucesso!");
            this.carregarProdutos();
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao excluir o produto.", "ERRO", JOptionPane.ERROR_MESSAGE);
        };
    }//GEN-LAST:event_jbExcluirProdutoActionPerformed

    private void jbNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNovoProdutoActionPerformed
        // TODO add your handling code here:
        changeHabilitarCampos(true);
        salvarAlterar = "salvar";
    }//GEN-LAST:event_jbNovoProdutoActionPerformed

    private void jbCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarProdutoActionPerformed
        // TODO add your handling code here:
        changeHabilitarCampos(false);
        limparCampos();
    }//GEN-LAST:event_jbCancelarProdutoActionPerformed

    private void jbEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarProdutoActionPerformed
        // TODO add your handling code here:
        salvarAlterar = "alterar";
        this.changeHabilitarCampos(true);
        int linhaSelecionada = this.jtProduto.getSelectedRow();
        try {
        int codigoProdutoSelecionado = (int) jtProduto.getValueAt(linhaSelecionada, 0);
            //recuperando produto do banco
            modelProdutos = controllerProdutos.retornarProdutoController(codigoProdutoSelecionado);
            
            //setar dados na interface
            this.jtfCodigoProduto.setText(String.valueOf(modelProdutos.getIdProduto()));
            this.jtfNomeProduto.setText(modelProdutos.getProdutoNome());
            this.jtfValorProduto.setText(String.valueOf(modelProdutos.getProdutoValor()));
            this.jtfEstoqueProduto.setText(String.valueOf(modelProdutos.getProdutoEstoque()));
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Código de produto inválido.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jbEditarProdutoActionPerformed

    private void jtfPesquisarProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPesquisarProdutoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == VK_ENTER) {
            this.pesquisarProduto();
        }
    }//GEN-LAST:event_jtfPesquisarProdutoKeyPressed

    private void jtProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtProdutoMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = this.jtProduto.getSelectedRow();
        try {
        int codigoProdutoSelecionado = (int) jtProduto.getValueAt(linhaSelecionada, 0);
            //recuperando produto do banco
            modelProdutos = controllerProdutos.retornarProdutoController(codigoProdutoSelecionado);
            
            //setar dados na interface
            this.jtfCodigoProduto.setText(String.valueOf(modelProdutos.getIdProduto()));
            this.jtfNomeProduto.setText(modelProdutos.getProdutoNome());
            this.jtfValorProduto.setText(String.valueOf(modelProdutos.getProdutoValor()));
            this.jtfEstoqueProduto.setText(String.valueOf(modelProdutos.getProdutoEstoque()));
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Código de produto inválido.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
        this.changeHabilitarCampos(false);
    }//GEN-LAST:event_jtProdutoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProduto().setVisible(true);
            }
        });
    }
    /**
     * Modifica a condição de habilitado dos campos do formulario
     * @param condicao 
     */
    private void changeHabilitarCampos(boolean condicao) {
        jtfNomeProduto.setEnabled(condicao);
        jtfEstoqueProduto.setEnabled(condicao);
        jtfValorProduto.setEnabled(condicao);
    }
    /**
     * Limpa os campos do formulario os deixando vazios
     *
     */
    private void limparCampos(){
        jtfCodigoProduto.setText("");
        jtfNomeProduto.setText("");
        jtfEstoqueProduto.setText("");
        jtfValorProduto.setText("");
    }
    
    /**
     * salva um produto no banco de dados
     */
    private void salvarProduto() {
        //Salva um produto no banco de dados
        modelProdutos.setProdutoNome(this.jtfNomeProduto.getText());
        modelProdutos.setProdutoEstoque(Integer.parseInt(this.jtfEstoqueProduto.getText()));
        modelProdutos.setProdutoValor(formatador.converteVirgulaParaPontoReturn(this.jtfValorProduto.getText()));
        if(controllerProdutos.salvarProdutosController(modelProdutos)>0) {
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
            this.carregarProdutos();
            this.limparCampos();
            this.changeHabilitarCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto." , "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }
 
    /**
     * altera um produto já cadastrado previamente
     */
    private void alterarProduto() {
        
        modelProdutos.setProdutoNome(this.jtfNomeProduto.getText());
        modelProdutos.setProdutoEstoque(Integer.parseInt(this.jtfEstoqueProduto.getText()));
        modelProdutos.setProdutoValor(formatador.converteVirgulaParaPontoReturn(this.jtfValorProduto.getText()));
        if(controllerProdutos.alterarProdutoController(modelProdutos)) {
            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!");
            this.carregarProdutos();
            this.limparCampos();
            this.changeHabilitarCampos(false);
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar produto." , "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        
    }
    
    /**
     * cria uma pesquisa com base na entrada de dados do usuário
     */
    private void pesquisarProduto() {
        DefaultTableModel modelo = (DefaultTableModel) this.jtProduto.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jtProduto.setRowSorter(classificador);
        String textoPesquisa = jtfPesquisarProduto.getText();
        classificador.setRowFilter(RowFilter.regexFilter(textoPesquisa, 1));
    }
    
    /**
     * Preenche a tabela de produtos com os produtos do banco de dados
     */
    private void carregarProdutos() {
        listaModelProdutos = controllerProdutos.retornarListaProdutosController();
        DefaultTableModel modelo = (DefaultTableModel) jtProduto.getModel();
        modelo.setNumRows(0);
        //inserindo produtos na tabela
        int cont =  listaModelProdutos.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelProdutos.get(i).getIdProduto(),
                listaModelProdutos.get(i).getProdutoNome(),
                listaModelProdutos.get(i).getProdutoValor(),
                listaModelProdutos.get(i).getProdutoEstoque(),
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelarProduto;
    private javax.swing.JButton jbEditarProduto;
    private javax.swing.JButton jbExcluirProduto;
    private javax.swing.JButton jbNovoProduto;
    private javax.swing.JButton jbPesquisarProduto;
    private javax.swing.JButton jbSalvarProduto;
    private javax.swing.JTable jtProduto;
    private javax.swing.JTextField jtfCodigoProduto;
    private javax.swing.JFormattedTextField jtfEstoqueProduto;
    private javax.swing.JTextField jtfNomeProduto;
    private javax.swing.JTextField jtfPesquisarProduto;
    private javax.swing.JFormattedTextField jtfValorProduto;
    // End of variables declaration//GEN-END:variables
}
